# -*- coding: utf-8 -*-
"""Colab'e hoş geldiniz.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# DSA 210 - Introduction to Data Science
# Final Project: Sci-Fi & Fantasy Book Adaptations Analysis & Prediction
# Author: İsmail Aydın
# Date: May 18, 2026


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings

# Machine Learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Suppress warnings for clean output
warnings.filterwarnings('ignore')


# 1. DATA COLLECTION & PREPARATION

print("=== PHASE 1: DATA COLLECTION & PREPARATION ===")
try:
    movies_df = pd.read_csv('tmdb_5000_movies.csv')
    books_df = pd.read_csv('books.csv')
    print("[SUCCESS] Datasets loaded successfully!")
except FileNotFoundError:
    print("[ERROR] Please make sure 'tmdb_5000_movies.csv' and 'books.csv' are in the same directory.")
    exit()

# Filter TMDB dataset for Science Fiction and Fantasy movies
sf_fantasy_movies = movies_df[movies_df['genres'].str.contains('Science Fiction|Fantasy', na=False)]

# Handling title mismatches (Mapping flagships)
title_mapping = {
    "The Lord of the Rings: The Fellowship of the Ring": "The Fellowship of the Ring",
    "Harry Potter and the Philosopher's Stone": "Harry Potter and the Sorcerer's Stone"
}
sf_fantasy_movies['mapped_title'] = sf_fantasy_movies['title'].replace(title_mapping)

# Merge the datasets using the mapped titles
merged_df = pd.merge(sf_fantasy_movies, books_df, left_on='mapped_title', right_on='book_title', how='inner')

# Data Cleansing: Remove NaN values and non-positive financial values
merged_df = merged_df.dropna(subset=['revenue', 'budget', 'book_rating'])
merged_df = merged_df[merged_df['revenue'] > 0]
merged_df = merged_df[merged_df['budget'] > 0]
print(f"Total rows available after integration and cleansing: {len(merged_df)}\n")


# 2. EXPLORATORY DATA ANALYSIS (EDA)

print("=== PHASE 2: EXPLORATORY DATA ANALYSIS (EDA) ===")
sns.set_theme(style="whitegrid")
plt.figure(figsize=(18, 5))

# Plot 1: Distribution of Box Office Revenue
plt.subplot(1, 3, 1)
sns.histplot(merged_df['revenue'], bins=15, kde=True, color='royalblue')
plt.title('Movie Box Office Revenue Distribution')
plt.xlabel('Revenue ($)')
plt.ylabel('Frequency')

# Plot 2: Goodreads Book Rating vs Movie Revenue
plt.subplot(1, 3, 2)
sns.scatterplot(data=merged_df, x='book_rating', y='revenue', alpha=0.7, color='darkorchid', s=60)
plt.title('Goodreads Book Rating vs. Movie Revenue')
plt.xlabel('Goodreads Book Rating (out of 5)')
plt.ylabel('Movie Revenue ($)')

# Plot 3: Movie Budget vs Movie Revenue
plt.subplot(1, 3, 3)
sns.scatterplot(data=merged_df, x='budget', y='revenue', alpha=0.7, color='forestgreen', s=60)
plt.title('Movie Budget vs. Movie Revenue')
plt.xlabel('Budget ($)')
plt.ylabel('Revenue ($)')

plt.tight_layout()
print("[INFO] Displaying EDA plots...")
plt.show()


# 3. HYPOTHESIS TESTING

print("\n=== PHASE 3: HYPOTHESIS TESTING ===")
# Splitting data into High-Rated (>= 4.0) and Low-Rated (< 4.0) books
high_rated_books = merged_df[merged_df['book_rating'] >= 4.0]['revenue']
low_rated_books = merged_df[merged_df['book_rating'] < 4.0]['revenue']

print(f"Sample size of High-Rated Book Adaptations: {len(high_rated_books)}")
print(f"Sample size of Low-Rated Book Adaptations: {len(low_rated_books)}")

# Perform an Independent Two-Sample T-Test (Welch's T-Test due to unequal variances)
t_stat, p_value = stats.ttest_ind(high_rated_books, low_rated_books, equal_var=False)
print(f"Computed T-Statistic: {t_stat:.4f}")
print(f"Computed P-Value: {p_value:.4f}")

alpha = 0.05
print("\n--- Statistical Conclusion ---")
if p_value < alpha:
    print("Result: Reject the Null Hypothesis (P-value < 0.05).")
    print("Conclusion: There is a statistically significant difference in revenue between high and low rated book adaptations.")
else:
    print("Result: Fail to Reject the Null Hypothesis (P-value >= 0.05).")
    print("Conclusion: A high book rating DOES NOT yield a statistically significant difference in a movie's box office revenue.\n")


# 4. MACHINE LEARNING: REVENUE PREDICTION

print("=== PHASE 4: MACHINE LEARNING ===")

# Define predictor variables (Features) and target variable
features = ['budget', 'book_rating']
X = merged_df[features]
y = merged_df['revenue']

# Split dataset into Training (80%) and Testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# --- Model 1: Linear Regression ---
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
lr_predictions = lr_model.predict(X_test)
lr_r2 = r2_score(y_test, lr_predictions)
print(f"[MODEL] Linear Regression R-squared Score: {lr_r2:.4f}")

# --- Model 2: Random Forest Regressor ---
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)
rf_r2 = r2_score(y_test, rf_predictions)
print(f"[MODEL] Random Forest Regressor R-squared Score: {rf_r2:.4f}")

# Plotting Actual vs Predicted Revenue for Random Forest
plt.figure(figsize=(8, 6))
plt.scatter(y_test, rf_predictions, alpha=0.8, color='darkorange', edgecolors='black', s=50)
# Perfect prediction diagonal line
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect Prediction Line')
plt.title('Machine Learning: Actual vs Predicted Revenue (Random Forest)')
plt.xlabel('Actual Box Office Revenue ($)')
plt.ylabel('Predicted Box Office Revenue ($)')
plt.legend()
plt.grid(True)
print("[INFO] Displaying ML Model Evaluation plot...")
plt.show()
print("==============================================================================")